name: Laravel CI Pipeline

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master"]]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel_test
          MYSQL_ROOT_PASSWORD: root 
        ports:
          - 3306:3306
        options: >- 
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shiva,,athur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql, pdo_mysql, curl, zip

      - name: Copy .env file 
        run: cp .env.example .env

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: php artisan key:generate 

      - name: Set up database environment
        run: 
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env    
          sed -i 's/DB_PORT=3306/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=laravel_test/DB_DATABASE=laravel_test/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=root/DB_PASSWORD=root/' .env

      - name: Run Database Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: php atisan test